### ISSUE TITLE
Perhaps an -L flag is missing?

### ISSUE THREAD

**Issue by tbraun96** [dstebila/oqs-rs#1]
Compiling on host x86_64-windows-pc-msvc returns an error:

```
Compiling oqs-sys v0.1.0 (C:\foo\oqs-rs\oqs-sys)
Compiling oqs v0.1.0 (C:\foo\oqs-rs\oqs)
error: could not find native static library `oqs`, perhaps an -L flag is missing?
```

(On a side note, I merely cloned the repo and tried running a simple unit test in a parent crate):
```
    #[test]
    fn test_oqs() {
        oqs::init();
        let alice = oqs::kem::Kem::new(oqs::kem::Algorithm::Firesaber).unwrap();
        let (public_key, secret_key) = alice.keypair().unwrap();

        let bob = oqs::kem::Kem::new(oqs::kem::Algorithm::Firesaber).unwrap();
        let (ciphertext, bob_symmetric_key) = bob.encapsulate(public_key.as_ref()).unwrap();
        let alice_symmetric_key = alice.decapsulate(secret_key.as_ref(), ciphertext.as_ref()).unwrap();
        assert_eq!(alice_symmetric_key.as_ref(), bob_symmetric_key.as_ref());
    }
```

Took a look at the codebase - code looks sharp. Well done. Would really like to get this to work to replace your pqcrypto crate for "real world" purposes (startup).

**Comment by thomwiggers** [comment]
I don't run Windows and it worked on CI™ so I don't know how to fix that.

**Comment by thomwiggers** [comment]
What is your `[dependencies]` section for `oqs`? You should only need to add 

```toml
[dependencies]
oqs = { git = "https://github.com/dstebila/oqs-rs.git" }
```

**Comment by thomwiggers** [comment]
> for "real world" purposes (startup).

I should point out that all of the code involved has not been properly reviewed, or audited, and a lot of it is of not-super-great quality. Implementation flaws should be expected, we and other people in the community have already found them on several occasions. Caveat emptor.

**Comment by tbraun96** [comment]
Looks like the issue is related to nested workspaces. Nothing on your side of things.

> I should point out that all of the code involved has not been properly reviewed, or audited

I'll be getting a security audit pretty soon. When this happens, I'll make sure this crate gets reviewed (if you're open to that). This will a good way to establish credibility for both of us, and funded by VCs, not us.

**Comment by thomwiggers** [comment]
> I'll make sure this crate gets reviewed (if you're open to that). 

You would need to (get) reviewed all of the code in https://github.com/open-quantum-safe/; which is highly technical and extremely specialist; but sure.
